### ISSUE TITLE
Error in the Docker Command Line Interface after installing Docker 

### ISSUE THREAD

**Issue by tanujdhiman** [adv4000/docker#2]
**Error with pre-create check: "This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory"**

I am using Docker Command line Interface to make a network. But I am facing this error in the Docker quickstart terminal. Can you guys please suggest what to do when getting this error.

**Comment by adv4000** [comment]
Enable VT-X/AMD-v in your computer BIOS
